### ISSUE TITLE
Edit Invoice Status Change trigger - Additional Status should be a Checkbox type, not a select

### ISSUE THREAD

**Issue by astupidmoose** [btcpayserver/btcTransmuter#24]
Currently this is set to force users to select Any type of additional status, or a single one. 

I think it would make most sense for this to be a checkbox system and allow the merchants to customize which cases they will allow this to trigger on. 

In my instance, I would never trigger on PaidPartial, but would trigger on all other instances.

**Comment by Kukks** [comment]
You owe me a beer

**Comment by astupidmoose** [comment]
When selecting no additional statuses, the trigger reads: 
"Btcpayserver Invoice Status Change to paid and additional status to **_any_** status"

Shouldn't this be "Btcpayserver Invoice Status Change to paid and **_no additional status_**"?

I tried to select all, however invoices stopped selling funds, so I assume this is looking for PAID + Additional statuses?

**Comment by Kukks** [comment]
I've redone this trigger to be able to handle any scenario. Will be available in .25
