### ISSUE TITLE
Possibility to set the default view of recipes (list or cards)

### ISSUE THREAD

**Issue by wtzr** [btcpayserver/btcTransmuter#53]
We currently have around 8 active recipes, and the default "cards view" of the recipes is not very insightful anymore. To keep the overview I prefer the list view, and it would be nice to set this as a default in the settings. Currently we always have to switch to list view before we can alter any recipes quickly. 

In my opinion the list view should also be the default setting. It's much more structured.

**Comment by britttttk** [comment]
I agree, list view by default would be better @wtzr
