### ISSUE TITLE
kraken the XBTEUR pair is missing

### ISSUE THREAD

**Issue by darkban** [btcpayserver/btcTransmuter#63]
When I want to create a sales evendo on kraken the XBTEUR pair is missing

**Comment by Kukks** [comment]
Try `XXBTZEUR` 
Don't ask me why Kraken has such weird pair names in their API..

**Comment by NicolasDorier** [comment]
@Kukks you could use BTCPayServer.Ratings as a library now the dependency is broken with .Common.

**Comment by Kukks** [comment]
Nah my usage of ExchangeSharp in here is more broad since I allow trades and balance queries

**Comment by Klixtos** [comment]
Ran into this too... The request does goes through but is answered as XXBTZEUR .. hence :

` JToken ticker = apiTickers[marketSymbol];`  is null  
 
and so to move on with life:

` protected override async Task<ExchangeTicker> OnGetTickerAsync(string marketSymbol)
        {
            JToken apiTickers = await MakeJsonRequestAsync<JToken>("/0/public/Ticker", null, new Dictionary<string, object> { { "pair", NormalizeMarketSymbol(marketSymbol) } });
            JToken ticker = apiTickers[marketSymbol];
			if (ticker == null)
			{
				throw new APIException("Kraken is messing with you .... again...");
			}
            return await ConvertToExchangeTickerAsync(marketSymbol, ticker);
        }`
