### ISSUE TITLE
bug with login & account lockout.

### ISSUE THREAD

**Issue by Eskyee** [btcpayserver/btcTransmuter#68]
btcTransmuter latest version. 
been testing transmuter over the year. and every now and then I get account lockout.
not sure if this is bug with safari and cookies etc,  I've have not tested or reproduced with other browsers.

**Comment by britttttk** [comment]
From mattermost:
![image](https://user-images.githubusercontent.com/39231115/87509869-af000c80-c62f-11ea-87d9-bc237e0b7e50.png)

**Comment by britttttk** [comment]
@Eskyee can you see if you have any logs

**Comment by uhlhosting** [comment]
I have same issue, no logs unnfortunatelly, i also removed the container, removed the volumes, and the issue persisted, gues the creds are stored outside of the btctransmuter docker in this case. Or it does not explain how the credentials were still stored after a removal and addition in docker, i also runned docker system prune and docker volume prune .

**Comment by Eskyee** [comment]
Closing now, since kukks has updated Transmuter.
