### ISSUE TITLE
feature request - email password reset - btcTransmuter

### ISSUE THREAD

**Issue by Eskyee** [btcpayserver/btcTransmuter#69]
would love this to be added in btcTransmuter - email password reset
if a user account locked out happens.  or a forgotten password.

very important for most users wanting to keep their. settings and recipes.
thanks

**Comment by Kixunil** [comment]
Should be opt-in, otherwise the e-mail provider and anyone in the route between sending SMTP and the destination can abuse it to access BTCPay, read private information and possibly steal from hot wallets.

Password managers with backups are superior.
