### ISSUE TITLE
Transmuter Not Pairing with URL

### ISSUE THREAD

**Issue by JMadisonTP** [btcpayserver/btcTransmuter#73]
Hello All,

I am running btcpay on a RPi3 with docker. Running latest version of btcpay.
I add this via CLI in docker:
export BTCPAYGEN_ADDITIONAL_FRAGMENTS="$BTCPAYGEN_ADDITIONAL_FRAGMENTS;opt-add-btctransmuter"

Im following the guide provided. 
I go to presets to begin the process.
when i get to the pairing section, i input my URL hit "save" but i get a 504 gateway time-out error nginx.
my URL is a subdomain, of my root domain. its how i log into btcpay (via the subdomain)

I use a subdomain because of the guide for RPi3 deployment where it says this:
export BTCPAY_HOST="btcpay.YourDomain.com"

anyone have any ideas?

**Comment by BitizenOne** [comment]
In case you are still interested, I believe I may have solved a similar issue here: https://github.com/btcpayserver/btcTransmuter/issues/96#issuecomment-1083272261
