### ISSUE TITLE
Trading agreement for Generated_FiatExchangeConversion at kraken

### ISSUE THREAD

**Issue by b068931cc450442b63f5b3d276ea4297** [btcpayserver/btcTransmuter#89]
The Generated_FiatExchangeConversion function seems to require a confirmation of the trading agreement for each API usage with the BTC Transmuter and the usage of Kraken as a person with address in Germany. More information from Kraken:

> If your Kraken account is verified with a German address, you will need to accept a trading
> agreement (shown below) in order to place market and margin orders.

https://support.kraken.com/hc/en-us/articles/360036157952
https://support.kraken.com/hc/en-us/articles/360000920026--Trading-agreement-required-error-for-German-residents

Is there any way to include this confirmation? Unfortunately I could not find anything.

The exact message in the logs is:

~~~
Could not place order because EOrder:Trading agreement required. Order details: {"MarketSymbol": "XXMRZEUR", "Amount":0.07000311, "Price":0.0, "StopPrice":0.0, "IsBuy":false, "IsMargin":false, "OrderId":null, "ClientOrderId":null, "ShouldRoundAmount":false, "OrderType":1, "ExtraParameters":{}}
~~~

**Comment by b068931cc450442b63f5b3d276ea4297** [comment]
@Kukks do you have any idea?

**Comment by Kukks** [comment]
No clue, it is possible that you need to do something on the kraken
website.

**Comment by b068931cc450442b63f5b3d276ea4297** [comment]
Thanks for your answer, unfortunately this is not possible. Kraken writes about this:

> If you trade via API, the trading agreement needs to be included in every relevant API call you make.

Can it perhaps be included as an option in BtcTransmuter.Extension.Exchange/Actions/PlaceOrder/?

**Comment by b068931cc450442b63f5b3d276ea4297** [comment]
To bypass the confirmation of the trading agreement, you can use a limit order instead of a market order. A way to confirm the trading agreement with the btctransmuter would still be very helpful in the future.

**Comment by b068931cc450442b63f5b3d276ea4297** [comment]
Maybe this will solve the problem soon: https://github.com/jjxtra/ExchangeSharp/pull/573

**Comment by Kukks** [comment]
Solved in latest release
